apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: cert-sync
  namespace: certsync
spec:
  vault:
    name: preastus2-akv
    object:
      name: ExampleCertificate 
      type: certificate
  output:
    secret:
      name: nginx-cert
      type: kubernetes.io/tls
